# Generated by Django 5.2.12 on 2026-03-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(blank=True, choices=[('healing', 'Kundalini Transmissions, Soul Clearings & Intuitive Sessions'), ('intuitive', 'Intuitive Session Reviews')], default='healing', max_length=20),
        ),
    ]
