# Generated by Django 4.2.18 on 2026-04-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('kundalini', 'Remote Healings: Kundalini Energy Transmission'), ('spirit_rescue', 'Mediumship: Spirit Rescue'), ('intuitive', 'Intuitive Session')], max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('session_date', models.DateField()),
                ('location_or_platform', models.CharField(max_length=200)),
                ('agrees_to_terms', models.BooleanField(default=False)),
                ('typed_signature', models.CharField(max_length=200)),
                ('date_signed', models.DateField()),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_signature', models.CharField(blank=True, max_length=200)),
                ('guardian_date_signed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'consent submission',
                'verbose_name_plural': 'consent submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_format', models.CharField(choices=[('zoom', 'Zoom (Remote)'), ('in_person', 'In-Person (Seattle)'), ('phone', 'Phone / FaceTime')], max_length=20)),
                ('preferred_datetime', models.DateTimeField(blank=True, help_text='Preferred date and time for the session', null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='store.service')),
            ],
            options={
                'verbose_name': 'booking request',
                'verbose_name_plural': 'booking requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
