# Generated by Django 4.2.18 on 2026-04-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_consentsubmission_bookingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
